# apollo的配置
app:
  id: SampleApp
apollo:
  meta: http://localhost:8080              #应该选择tcp映射，而且，必须要加上 http
  config-service: http://localhost:8080    #apollo服务和访问者不在一个机器上，必须做这个处理
  bootstrap:
    enabled: true
    namespaces: application,testnamespace
    eagerLoad:
      enabled: true

# http方式 和tcp 方式，都可以访问apollo
#app:
#  id: SampleApp
#apollo:
#  meta: http://testapollo.sv1.k9s.run:2271              #应该选择tcp映射，而且，必须要加上 http
#  config-service: http://testapollo.sv1.k9s.run:2271    #apollo服务和访问者不在一个机器上，必须做这个处理
#  bootstrap:
#    enabled: true
#    namespaces: application,testnamespace
#    eagerLoad:
#      enabled: true

#mysql的配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://sv1.k9s.run:13345/ApolloPortalDB?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
#    username: newuser
#    password: Ls981592@


# 连接远程数据库  1、检查内存穿透是否打开     2、要在workbench users and Privileges 中配置权限 新增一个  user/%  Limit to Hosts Matching
spring:

  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ApolloPortalDB?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 201642



  #kafka
  #启动kafka：1、先进入zk的目录，点击zkServer.cmd  2、进入kafka的目录，进入终端   bin\windows\kafka-server-start.bat config\server.properties
  #查看topic之类： 3、另开一个终端， bin\windows\kafka-topics.bat --list --bootstrap-server localhost:9092
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092 # 会覆盖 spring.kafka.bootstrap-servers 配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 序列化key的类
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # 反序列化value的类
    consumer:
      bootstrap-servers: localhost:9092 # 会覆盖 sp
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # 反序列化key的类
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # 反序列化value的类
      group-id: testgroup